_BASE_: "Base-MDR.yaml"
MODEL:
  WEIGHTS: "/data/zelinliu/MDR/output_mix20/model_mix20.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  MDR:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 1
    IS_TRAIN: True
    IS_FIX: True
    BOX_RATIO: (0.5, 1.5)
    USE_FOCAL_R: True
    MAX_FRAME_DIST: 10
    SAMPLER_STEPS: (26796, 53592, 80388) # 25  45  75
DATASETS:
  TEST:  ("my_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  STEPS: (53592, 80388) # 2233 -- 1 eps
  MAX_ITER: 107184 # 12 12 12 12 -- bs = 4
  CHECKPOINT_PERIOD: 2500
  AMP:
    ENABLED: False # 暂时不支持混合精度训练 以及 半精度推理
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0001
DATALOADER:
  NUM_WORKERS: 4
TEST:
  EVAL_PERIOD: 10000000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800, 832, 864)
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1500
  CROP:
    ENABLED: False
  FORMAT: "RGB"
OUTPUT_DIR: "output_mix20_track" 

