_BASE_: "Base-MDR.yaml"
MODEL:
  WEIGHTS: "/data/zelinliu/MDR/output_track_dance/model_0139999.pth" #169999 -- 【189999，199999，224999， 229999， 144999】
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  MDR:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 1
    IS_TRAIN: True
    IS_FIX: True
    TRACKING: True
    TRACKING_SCORE: 0.25 # 20 - 6 8
    BOX_RATIO: (0.5, 1.5)
    MIX_AREA: 100
    USE_FOCAL_R: True
    MAX_FRAME_DIST: 10 
    NEW_TRACKING_THRES: 0.8 # 20 - 6 8
    
DATASETS:
  TEST:  ("my_val",)
SOLVER:
  IMS_PER_BATCH: 1
  STEPS: (15629, 18606) # 558
  MAX_ITER: 20095
  CHECKPOINT_PERIOD: 5000
  AMP:
    ENABLED: False # 暂时不支持混合精度训练 以及 半精度推理
DATALOADER:
  NUM_WORKERS: 1
TEST:
  EVAL_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800, 832, 864)
  MAX_SIZE_TRAIN: 1620
  MIN_SIZE_TEST: 800 # 20 - 6 8
  MAX_SIZE_TEST: 1500 # 20 - 6 8
  CROP:
    ENABLED: False
  FORMAT: "RGB"
OUTPUT_DIR: "output_dance_track_infer" 

