_BASE_: "Base-MDR.yaml"
MODEL:
  # WEIGHTS: "/data/zelinliu/MDR/output_mix20/model_mix20.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  MDR:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 1
    IS_TRAIN: True
    IS_FIX: False
    BOX_RATIO: (0.5, 1.5)
    USE_FOCAL_R: True
    MAX_FRAME_DIST: 10
    SAMPLER_STEPS: (51745, 102490, 152235)
    D_STATE: 256
    EXPAND: 1
DATASETS:
  TEST:  ("my_val",)
  TRAIN_DATA_IMG_PATH: "/data/zelinliu/DanceTrack/dancetrack/train"
  TRAIN_DATA_ANN_PATH: "/data/zelinliu/DanceTrack/dancetrack/annotations/train.json"
  TRAIN_DATA_SAMPLER_LEN: (2,4,6,8)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  STEPS: (122388, )
  MAX_ITER: 200980 
  CHECKPOINT_PERIOD: 5000
  AMP:
    ENABLED: False # 暂时不支持混合精度训练 以及 半精度推理
DATALOADER:
  NUM_WORKERS: 4
TEST:
  EVAL_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800, 832, 864)
  MAX_SIZE_TRAIN: 1620
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1500
  CROP:
    ENABLED: False
  FORMAT: "RGB"
OUTPUT_DIR: "output_track_dance" 

