_BASE_: "Base-MDR.yaml"
MODEL:
  WEIGHTS: "/data/zelinliu/MDR/resnet50-0676ba61.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  MDR:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 1
DATASETS:
  TEST:  ("my_val",)
SOLVER:
  STEPS: (49532, 58966) # 1769
  MAX_ITER: 63684 #1769*36
  CHECKPOINT_PERIOD: 5000
  AMP:
    ENABLED: False # 暂时不支持混合精度训练 以及 半精度推理
TEST:
  EVAL_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800, 832, 864)
  MAX_SIZE_TRAIN: 1620
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1500
  CROP:
    ENABLED: False
  FORMAT: "RGB"
OUTPUT_DIR: "output_mix20"