eps: 0.001
#eval_mode: False
eval_mode: True
use_diffmot: False

# optimizer
lr: 0.0001
# train
data_dir: "/data/zelinliu/mot/trackers_gt"
diffnet: HMINet
interval: 5 #5
augment: True
encoder_dim: 256
tf_layer: 3
epochs: 800
batch_size: 2048
seed: 123
eval_every: 20
gpus: [0,]

# Testings  
eval_at: 160 # 100-74.146 260-74.597 460-74.436
det_dir: "/data/zelinliu/MOT17/detections/train"
info_dir: "/data/zelinliu/MOT17/train"
reid_dir: "/data/zelinliu/TrackSSM/cache/embeddings/"
save_dir: "/data/zelinliu/TrackSSM/results/val/yolox_m_lt_ept"
eval_expname: mot_ddm_1000_deeper
show_image: False
use_detection_model: False
det_ckpt: "bytetrack_x_mot17.pth.tar"
exp_path: "external/YOLOX/exps/mot/yolox_x_mix_det.py"
high_thres: 0.6                                                                                                                                                                                           
low_thres: 0.1
w_assoc_emb: 2.2
aw_param: 1.7
preprocess_workers: 16

# Data Parameters:
device: cuda
eval_device: None
