eps: 0.001
#eval_mode: False
eval_mode: True

# optimizer
lr: 0.0001
# train
data_dir: "/data/zelinliu/mot/trackers_gt"
diffnet: HMINet
interval: 5
augment: True
encoder_dim: 256
tf_layer: 3
epochs: 800
batch_size: 2048
seed: 123
eval_every: 20
gpus: [0,]

# Testing 280(74.596) 460（74.008）580（74.428） 600.  ||.  160(74.91). 260(74.41) 
eval_at: 720 # 80 100（74.48）280（74.39）460（74.59） 480 （74.99） 540(74.01) 560(74.04) 580(74.239). 640(74.364)  780(74.355) 800(74.545)
det_dir: "/data/zelinliu/MOT17/detections/train"
info_dir: "/data/zelinliu/MOT17/train"
reid_dir: "/data/zelinliu/DiffMOT/cache/embeddings/"
save_dir: "/data/zelinliu/DiffMOT/results/val/yolox_m_lt_ddm_1000eps_deeper_800_1rev_720ept"
eval_expname: mot_ddm_1000_deeper
high_thres: 0.6                                                                                                                                                                                           
low_thres: 0.1
w_assoc_emb: 2.2
aw_param: 1.7
preprocess_workers: 16

# Data Parameters:
device: cuda
eval_device: None
